# This is a basic workflow to help you get started with Actions

name: Python Greetings CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  PYTHON_GREETINGS_REPO: "mtararujs/python-greetings"
  PYTHON_GREETINGS_REF: "4e911440a9886c7c26ccbb4eb55f0bc2a5067b51"
  PYTHON_GREETINGS_DIR: "python-greetings"

jobs:

  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Starting Job
        run: echo "Installing pip dependencies"
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: ${{ env.PYTHON_GREETINGS_REPO }}
          path: ${{ env.PYTHON_GREETINGS_DIR }}
          ref: ${{ env.PYTHON_GREETINGS_REF }}
      - name: Install dependencies
        working-directory:  ${{ env.PYTHON_GREETINGS_DIR }}
        run: pip3 install -r requirements.txt 

  deploy-to-dev:
    runs-on: self-hosted
    needs: [install-pip-deps]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/deploy
        with:
          port: 7001
          enviroment: 'dev'
      
  tests-on-dev:
    runs-on: self-hosted
    needs: [deploy-to-dev]
    steps:
      - name: Starting Job
        run: echo "Testing on DEV"
        
  deploy-to-staging:
    runs-on: self-hosted
    needs: [tests-on-dev]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/deploy
        with:
          port: 7002
          enviroment: 'staging'
        
  tests-on-staging:
    runs-on: self-hosted
    needs: [deploy-to-staging]
    steps:
      - name: Starting Job
        run: echo "Testing on STAGING"
        
  deploy-to-preprod:
    runs-on: self-hosted
    needs: [tests-on-staging]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/deploy
        with:
          port: 7003
          enviroment: 'preprod'
        
  tests-on-preprod:
    runs-on: self-hosted
    needs: [deploy-to-preprod]
    steps:
      - name: Starting Job
        run: echo "Testing on PRE-PRODUCTION"
        
  deploy-to-prod:
    runs-on: self-hosted
    needs: [tests-on-preprod]
    steps:
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/deploy
        with:
          port: 7004
          enviroment: 'prod'
        
  Tests-on-prod:
    runs-on: self-hosted
    needs: [deploy-to-prod]
    steps:
      - name: Starting Job
        run: echo "Testing on PRODUCTION"
