# This is a basic workflow to help you get started with Actions

name: Python Greetings CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
env:
  PYTHON_GREETINGS_REPO: "mtararujs/python-greetings"
  PYTHON_GREETINGS_REF: "4e911440a9886c7c26ccbb4eb55f0bc2a5067b51"
  PYTHON_GREETINGS_DIR: "python-greetings"
  JS_API_FRAMEWORK_REPO: "mtararujs/course-js-api-framework"
  JS_API_FRAMEWORK_DIR: "js-api-framework"
  JS_API_FRAMEWORK_REF: "7032ee862638108d4b9ad455e25e92a846c01ece"

jobs:
  
  install-pip-deps:
    runs-on: self-hosted
    steps:
      - name: Prepare for Install
        run: "cmd /c \"pm2 delete all & set \\\"errorlevel=0\\\"\"" # Nepieciešams, jo github mēģina sākumā izdzēst repo folderi bet nevar, ja no turienes jau ir palaistas programmas
      - uses: actions/checkout@v3.5.2
      - uses: ./.github/actions/install

  deploy-to-dev:
    runs-on: self-hosted
    needs: [install-pip-deps]
    steps:
      - uses: ./.github/actions/deploy
        with:
          port: 7001
          enviroment: 'dev'
      
  tests-on-dev:
    runs-on: self-hosted
    needs: [deploy-to-dev]
    steps:
      - uses: ./.github/actions/test
        with:
          enviroment: 'dev'
        
  deploy-to-staging:
    runs-on: self-hosted
    needs: [tests-on-dev]
    steps:
      - uses: ./.github/actions/deploy
        with:
          port: 7002
          enviroment: 'staging'
        
  tests-on-staging:
    runs-on: self-hosted
    needs: [deploy-to-staging]
    steps:
      - uses: ./.github/actions/test
        with:
          enviroment: 'staging'
        
  deploy-to-preprod:
    runs-on: self-hosted
    needs: [tests-on-staging]
    steps:
      - uses: ./.github/actions/deploy
        with:
          port: 7003
          enviroment: 'preprod'
        
  tests-on-preprod:
    runs-on: self-hosted
    needs: [deploy-to-preprod]
    steps:
      - uses: ./.github/actions/test
        with:
          enviroment: 'preprod'
        
  deploy-to-prod:
    runs-on: self-hosted
    needs: [tests-on-preprod]
    steps:
      - uses: ./.github/actions/deploy
        with:
          port: 7004
          enviroment: 'prod'
        
  Tests-on-prod:
    runs-on: self-hosted
    needs: [deploy-to-prod]
    steps:
      - uses: ./.github/actions/test
        with:
          enviroment: 'prod'
